version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_raizen
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: raizen
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
